development:
  morphology: stem_en
  stopwords: 'config/stopwords.txt'
test:
  morphology: stem_en
  stopwords: 'config/stopwords.txt'
production:
  bin_path: '/home/jlcapps/bin'
  pid_file: '/home/jlcapps/webapps/rails/whowoulddowhich.com/shared/pids/searchd.pid'
  searchd_file_path: '/home/jlcapps/webapps/rails/whowoulddowhich.com/shared/db/sphinx'
  morphology: stem_en
  stopwords: 'config/stopwords.txt'
