development:
  morphology: stem_en
  stopwords: 'config/stopwords.txt'
test:
  morphology: stem_en
  stopwords: 'config/stopwords.txt'
production:
  searchd_file_path: '~/webapps/rails/wwnd/db/sphinx/production/'
  morphology: stem_en
  stopwords: 'config/stopwords.txt'
